apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiverservice-deployment
  namespace: receiver
  labels:
    app: receiverservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiverservice
  template:
    metadata:
      labels:
        app: receiverservice
    spec:
      initContainers:
        - name: init-javaagent
          image: curlimages/curl:8.7.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Downloading OpenTelemetry Java Agent..."
              curl -sSLf https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.16.0/opentelemetry-javaagent.jar -o /otel/opentelemetry-javaagent.jar
              echo "Download complete:"
              ls -lh /otel
          volumeMounts:
            - name: otel-javaagent
              mountPath: /otel

      containers:
        - name: receiverservice
          image: praveen581348/receiverservice:21
          ports:
            - containerPort: 8084
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.messaging.svc.cluster.local:9092"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://localhost:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_SERVICE_NAME
              value: receiverservice
          volumeMounts:
            - name: otel-javaagent
              mountPath: /otel

        - name: otel-sidecar
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--config=/conf/otel-config.yaml"]
          volumeMounts:
            - name: otel-config
              mountPath: /conf

      volumes:
        - name: otel-config
          configMap:
            name: otel-receiver-config
        - name: otel-javaagent
          emptyDir: {}
